/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiAdminAcademiesIdGet404Response } from '../model/models';
import { CreateAcademyDTO } from '../model/models';
import { PaginationAcademyDTO } from '../model/models';
import { ShowAcademyDTO } from '../model/models';
import { UpdateAcademyDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AcademyServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param name 
     * @param isActive 
     * @param createdFrom 
     * @param createdTo 
     * @param pageNumber 
     * @param pageSize 
     */
    apiAdminAcademiesGet(name?: string, isActive?: boolean, createdFrom?: string, createdTo?: string, pageNumber?: number, pageSize?: number, extraHttpRequestParams?: any): Observable<PaginationAcademyDTO>;

    /**
     * 
     * 
     * @param id 
     */
    apiAdminAcademiesIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiAdminAcademiesIdGet(id: string, extraHttpRequestParams?: any): Observable<ShowAcademyDTO>;

    /**
     * 
     * 
     * @param id 
     * @param updateAcademyDTO 
     */
    apiAdminAcademiesIdPut(id: string, updateAcademyDTO?: UpdateAcademyDTO, extraHttpRequestParams?: any): Observable<ShowAcademyDTO>;

    /**
     * 
     * 
     * @param createAcademyDTO 
     */
    apiAdminAcademiesPost(createAcademyDTO?: CreateAcademyDTO, extraHttpRequestParams?: any): Observable<ShowAcademyDTO>;

}
