/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiAdminContractsSendRenewalWarningsPostDaysAheadParameter } from '../model/models';
import { RenewalWarningsResultDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminContractServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param daysAhead 
     */
    apiAdminContractsSendRenewalWarningsPost(daysAhead?: ApiAdminContractsSendRenewalWarningsPostDaysAheadParameter, extraHttpRequestParams?: any): Observable<RenewalWarningsResultDTO>;

}
