/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiFrequencyGetPageParameter } from '../model/models';
import { GenerateFinancialTransactionsResultDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminAccountsReceivableServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param year 
     * @param month 
     */
    apiAdminMonthlyFeesGenerateChargesPost(year?: ApiFrequencyGetPageParameter, month?: ApiFrequencyGetPageParameter, extraHttpRequestParams?: any): Observable<GenerateFinancialTransactionsResultDTO>;

    /**
     * 
     * 
     * @param year 
     * @param month 
     */
    apiAdminMonthlyFeesGeneratePost(year?: ApiFrequencyGetPageParameter, month?: ApiFrequencyGetPageParameter, extraHttpRequestParams?: any): Observable<GenerateFinancialTransactionsResultDTO>;

}
