export * from './academy.service';
import { AcademyService } from './academy.service';
export * from './academy.serviceInterface';
export * from './accountsPayable.service';
import { AccountsPayableService } from './accountsPayable.service';
export * from './accountsPayable.serviceInterface';
export * from './accountsReceivable.service';
import { AccountsReceivableService } from './accountsReceivable.service';
export * from './accountsReceivable.serviceInterface';
export * from './address.service';
import { AddressService } from './address.service';
export * from './address.serviceInterface';
export * from './belt.service';
import { BeltService } from './belt.service';
export * from './belt.serviceInterface';
export * from './companyPersons.service';
import { CompanyPersonsService } from './companyPersons.service';
export * from './companyPersons.serviceInterface';
export * from './contract.service';
import { ContractService } from './contract.service';
export * from './contract.serviceInterface';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './dashboard.serviceInterface';
export * from './feePlan.service';
import { FeePlanService } from './feePlan.service';
export * from './feePlan.serviceInterface';
export * from './financialOverview.service';
import { FinancialOverviewService } from './financialOverview.service';
export * from './financialOverview.serviceInterface';
export * from './frequency.service';
import { FrequencyService } from './frequency.service';
export * from './frequency.serviceInterface';
export * from './graduation.service';
import { GraduationService } from './graduation.service';
export * from './graduation.serviceInterface';
export * from './graduationRequirements.service';
import { GraduationRequirementsService } from './graduationRequirements.service';
export * from './graduationRequirements.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './individualPersons.service';
import { IndividualPersonsService } from './individualPersons.service';
export * from './individualPersons.serviceInterface';
export * from './lesson.service';
import { LessonService } from './lesson.service';
export * from './lesson.serviceInterface';
export * from './lessonSchedule.service';
import { LessonScheduleService } from './lessonSchedule.service';
export * from './lessonSchedule.serviceInterface';
export * from './medicalClearance.service';
import { MedicalClearanceService } from './medicalClearance.service';
export * from './medicalClearance.serviceInterface';
export * from './notices.service';
import { NoticesService } from './notices.service';
export * from './notices.serviceInterface';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './notification.serviceInterface';
export * from './paymentWebhook.service';
import { PaymentWebhookService } from './paymentWebhook.service';
export * from './paymentWebhook.serviceInterface';
export * from './public.service';
import { PublicService } from './public.service';
export * from './public.serviceInterface';
export * from './publicContract.service';
import { PublicContractService } from './publicContract.service';
export * from './publicContract.serviceInterface';
export * from './scheduledJob.service';
import { ScheduledJobService } from './scheduledJob.service';
export * from './scheduledJob.serviceInterface';
export * from './students.service';
import { StudentsService } from './students.service';
export * from './students.serviceInterface';
export * from './supplier.service';
import { SupplierService } from './supplier.service';
export * from './supplier.serviceInterface';
export * from './tenantSettings.service';
import { TenantSettingsService } from './tenantSettings.service';
export * from './tenantSettings.serviceInterface';
export * from './transactionCategory.service';
import { TransactionCategoryService } from './transactionCategory.service';
export * from './transactionCategory.serviceInterface';
export const APIS = [AcademyService, AccountsPayableService, AccountsReceivableService, AddressService, BeltService, CompanyPersonsService, ContractService, DashboardService, FeePlanService, FinancialOverviewService, FrequencyService, GraduationService, GraduationRequirementsService, HealthService, IndividualPersonsService, LessonService, LessonScheduleService, MedicalClearanceService, NoticesService, NotificationService, PaymentWebhookService, PublicService, PublicContractService, ScheduledJobService, StudentsService, SupplierService, TenantSettingsService, TransactionCategoryService];
