export * from './academy.service';
import { AcademyService } from './academy.service';
export * from './academy.serviceInterface';
export * from './adminContract.service';
import { AdminContractService } from './adminContract.service';
export * from './adminContract.serviceInterface';
export * from './adminMonthlyFee.service';
import { AdminMonthlyFeeService } from './adminMonthlyFee.service';
export * from './adminMonthlyFee.serviceInterface';
export * from './adminNotification.service';
import { AdminNotificationService } from './adminNotification.service';
export * from './adminNotification.serviceInterface';
export * from './adminStudent.service';
import { AdminStudentService } from './adminStudent.service';
export * from './adminStudent.serviceInterface';
export * from './belt.service';
import { BeltService } from './belt.service';
export * from './belt.serviceInterface';
export * from './contract.service';
import { ContractService } from './contract.service';
export * from './contract.serviceInterface';
export * from './dashboard.service';
import { DashboardService } from './dashboard.service';
export * from './dashboard.serviceInterface';
export * from './feePlan.service';
import { FeePlanService } from './feePlan.service';
export * from './feePlan.serviceInterface';
export * from './financialTransaction.service';
import { FinancialTransactionService } from './financialTransaction.service';
export * from './financialTransaction.serviceInterface';
export * from './frequency.service';
import { FrequencyService } from './frequency.service';
export * from './frequency.serviceInterface';
export * from './graduation.service';
import { GraduationService } from './graduation.service';
export * from './graduation.serviceInterface';
export * from './graduationRequirements.service';
import { GraduationRequirementsService } from './graduationRequirements.service';
export * from './graduationRequirements.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './lesson.service';
import { LessonService } from './lesson.service';
export * from './lesson.serviceInterface';
export * from './medicalClearance.service';
import { MedicalClearanceService } from './medicalClearance.service';
export * from './medicalClearance.serviceInterface';
export * from './monthlyFee.service';
import { MonthlyFeeService } from './monthlyFee.service';
export * from './monthlyFee.serviceInterface';
export * from './notices.service';
import { NoticesService } from './notices.service';
export * from './notices.serviceInterface';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './notification.serviceInterface';
export * from './public.service';
import { PublicService } from './public.service';
export * from './public.serviceInterface';
export * from './students.service';
import { StudentsService } from './students.service';
export * from './students.serviceInterface';
export * from './transactionCategory.service';
import { TransactionCategoryService } from './transactionCategory.service';
export * from './transactionCategory.serviceInterface';
export const APIS = [AcademyService, AdminContractService, AdminMonthlyFeeService, AdminNotificationService, AdminStudentService, BeltService, ContractService, DashboardService, FeePlanService, FinancialTransactionService, FrequencyService, GraduationService, GraduationRequirementsService, HealthService, LessonService, MedicalClearanceService, MonthlyFeeService, NoticesService, NotificationService, PublicService, StudentsService, TransactionCategoryService];
