export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './belt.service';
import { BeltService } from './belt.service';
export * from './belt.serviceInterface';
export * from './frequency.service';
import { FrequencyService } from './frequency.service';
export * from './frequency.serviceInterface';
export * from './graduation.service';
import { GraduationService } from './graduation.service';
export * from './graduation.serviceInterface';
export * from './graduationRequirements.service';
import { GraduationRequirementsService } from './graduationRequirements.service';
export * from './graduationRequirements.serviceInterface';
export * from './health.service';
import { HealthService } from './health.service';
export * from './health.serviceInterface';
export * from './lesson.service';
import { LessonService } from './lesson.service';
export * from './lesson.serviceInterface';
export * from './medicalClearance.service';
import { MedicalClearanceService } from './medicalClearance.service';
export * from './medicalClearance.serviceInterface';
export * from './notices.service';
import { NoticesService } from './notices.service';
export * from './notices.serviceInterface';
export * from './notification.service';
import { NotificationService } from './notification.service';
export * from './notification.serviceInterface';
export * from './students.service';
import { StudentsService } from './students.service';
export * from './students.serviceInterface';
export const APIS = [AuthService, BeltService, FrequencyService, GraduationService, GraduationRequirementsService, HealthService, LessonService, MedicalClearanceService, NoticesService, NotificationService, StudentsService];
