/**
 * Carlson Gracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: support@carlsongracie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiAuthLoginPost401Response } from '../model/models';
import { CreateBeltDTO } from '../model/models';
import { ShowBeltDTO } from '../model/models';
import { UpdateBeltDTO } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface BeltServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get all belts
     * 
     */
    apiBeltGet(extraHttpRequestParams?: any): Observable<Array<ShowBeltDTO>>;

    /**
     * Delete a belt
     * 
     * @param id The belt ID to delete
     */
    apiBeltIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a specific belt by ID
     * 
     * @param id The belt ID
     */
    apiBeltIdGet(id: string, extraHttpRequestParams?: any): Observable<ShowBeltDTO>;

    /**
     * Update an existing belt
     * 
     * @param id The belt ID to update
     * @param updateBeltDTO The updated belt data
     */
    apiBeltIdPut(id: string, updateBeltDTO?: UpdateBeltDTO, extraHttpRequestParams?: any): Observable<ShowBeltDTO>;

    /**
     * Create a new belt
     * 
     * @param createBeltDTO The belt data to create
     */
    apiBeltPost(createBeltDTO?: CreateBeltDTO, extraHttpRequestParams?: any): Observable<ShowBeltDTO>;

}
