/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiAdminAcademiesIdGet404Response } from '../model/models';
import { ContractStatus } from '../model/models';
import { CreateContractDTO } from '../model/models';
import { ShowContractDTO } from '../model/models';
import { ShowContractDTOPaginatedResult } from '../model/models';
import { UpdateContractStatusRequest } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ContractServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param status 
     * @param studentId 
     * @param feePlanId 
     * @param startDateFrom 
     * @param startDateTo 
     * @param endDateFrom 
     * @param endDateTo 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiContractGet(status?: ContractStatus, studentId?: string, feePlanId?: string, startDateFrom?: string, startDateTo?: string, endDateFrom?: string, endDateTo?: string, page?: number, pageSize?: number, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<ShowContractDTOPaginatedResult>;

    /**
     * 
     * 
     * @param id 
     */
    apiContractIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiContractIdGet(id: string, extraHttpRequestParams?: any): Observable<ShowContractDTO>;

    /**
     * 
     * 
     * @param id 
     * @param updateContractStatusRequest 
     */
    apiContractIdStatusPatch(id: string, updateContractStatusRequest?: UpdateContractStatusRequest, extraHttpRequestParams?: any): Observable<ShowContractDTO>;

    /**
     * 
     * 
     * @param createContractDTO 
     */
    apiContractPost(createContractDTO?: CreateContractDTO, extraHttpRequestParams?: any): Observable<ShowContractDTO>;

}
