/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CarlonGracieBackendDTOsBarChartDataDTO } from '../model/models';
import { CarlonGracieBackendDTOsMonthlyNewStudentsDTO } from '../model/models';
import { CarlonGracieBackendDTOsStudentsBirthDay } from '../model/models';
import { CarlonGracieBackendDTOsTopStudentDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DashboardServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param days 
     */
    apiDashboardAttendanceGet(days?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param days 
     */
    apiDashboardBirthdaysGet(days?: number, extraHttpRequestParams?: any): Observable<Array<CarlonGracieBackendDTOsStudentsBirthDay>>;

    /**
     * 
     * 
     * @param days 
     */
    apiDashboardFrequencyBeltsDistributionGet(days?: number, extraHttpRequestParams?: any): Observable<CarlonGracieBackendDTOsBarChartDataDTO>;

    /**
     * 
     * 
     * @param months 
     */
    apiDashboardNewStudentsGet(months?: number, extraHttpRequestParams?: any): Observable<CarlonGracieBackendDTOsMonthlyNewStudentsDTO>;

    /**
     * 
     * 
     * @param days 
     */
    apiDashboardTopStudentsGet(days?: number, extraHttpRequestParams?: any): Observable<Array<CarlonGracieBackendDTOsTopStudentDTO>>;

}
