/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiFrequencyGetPageParameter } from '../model/models';
import { CreateFrequencyDTO } from '../model/models';
import { PaginatedResultOfShowFrequencyDTO } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ShowFrequencyDTO } from '../model/models';
import { ShowFrequencyUntilNextGraduationDTO } from '../model/models';
import { UpdateFrequencyDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FrequencyServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param studentId 
     * @param lessonId 
     * @param graduationId 
     * @param startDate 
     * @param endDate 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiFrequencyDateRangeGet(studentId?: string, lessonId?: string, graduationId?: string, startDate?: string, endDate?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowFrequencyDTO>;

    /**
     * 
     * 
     * @param studentId 
     * @param lessonId 
     * @param graduationId 
     * @param startDate 
     * @param endDate 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiFrequencyGet(studentId?: string, lessonId?: string, graduationId?: string, startDate?: string, endDate?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowFrequencyDTO>;

    /**
     * 
     * 
     * @param graduationId 
     * @param studentId 
     * @param lessonId 
     * @param graduationId2 
     * @param startDate 
     * @param endDate 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiFrequencyGraduationGraduationIdGet(graduationId: string, studentId?: string, lessonId?: string, graduationId2?: string, startDate?: string, endDate?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowFrequencyDTO>;

    /**
     * 
     * 
     * @param id 
     */
    apiFrequencyIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiFrequencyIdGet(id: string, extraHttpRequestParams?: any): Observable<ShowFrequencyDTO>;

    /**
     * 
     * 
     * @param id 
     * @param updateFrequencyDTO 
     */
    apiFrequencyIdPut(id: string, updateFrequencyDTO: UpdateFrequencyDTO, extraHttpRequestParams?: any): Observable<ShowFrequencyDTO>;

    /**
     * 
     * 
     * @param studentId 
     */
    apiFrequencyNextGraduationRequirementsStudentIdGet(studentId: string, extraHttpRequestParams?: any): Observable<ShowFrequencyUntilNextGraduationDTO>;

    /**
     * 
     * 
     * @param createFrequencyDTO 
     */
    apiFrequencyPost(createFrequencyDTO: CreateFrequencyDTO, extraHttpRequestParams?: any): Observable<ShowFrequencyDTO>;

    /**
     * 
     * 
     * @param userId 
     * @param studentId 
     * @param lessonId 
     * @param graduationId 
     * @param startDate 
     * @param endDate 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiFrequencyUserUserIdGet(userId: string, studentId?: string, lessonId?: string, graduationId?: string, startDate?: string, endDate?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowFrequencyDTO>;

}
