/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiFrequencyGetPageParameter } from '../model/models';
import { CreateGraduationDTO } from '../model/models';
import { PaginatedResultOfShowGraduationDTO } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ShowGraduationDTO } from '../model/models';
import { UpdateGraduationDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GraduationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param beltId 
     * @param studentId 
     * @param beltId2 
     * @param graduationDateFrom 
     * @param graduationDateTo 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiGraduationBeltBeltIdGet(beltId: string, studentId?: string, beltId2?: string, graduationDateFrom?: string, graduationDateTo?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowGraduationDTO>;

    /**
     * 
     * 
     * @param studentId 
     * @param beltId 
     * @param graduationDateFrom 
     * @param graduationDateTo 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiGraduationGet(studentId?: string, beltId?: string, graduationDateFrom?: string, graduationDateTo?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowGraduationDTO>;

    /**
     * 
     * 
     * @param id 
     */
    apiGraduationIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiGraduationIdGet(id: string, extraHttpRequestParams?: any): Observable<ShowGraduationDTO>;

    /**
     * 
     * 
     * @param id 
     * @param updateGraduationDTO 
     */
    apiGraduationIdPut(id: string, updateGraduationDTO: UpdateGraduationDTO, extraHttpRequestParams?: any): Observable<ShowGraduationDTO>;

    /**
     * 
     * 
     * @param createGraduationDTO 
     */
    apiGraduationPost(createGraduationDTO: CreateGraduationDTO, extraHttpRequestParams?: any): Observable<ShowGraduationDTO>;

    /**
     * 
     * 
     * @param userId 
     * @param studentId 
     * @param beltId 
     * @param graduationDateFrom 
     * @param graduationDateTo 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiGraduationUserUserIdGet(userId: string, studentId?: string, beltId?: string, graduationDateFrom?: string, graduationDateTo?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowGraduationDTO>;

}
