/**
 * BjjClutch Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiAdminAcademiesIdGet404Response } from '../model/models';
import { CreateGraduationRequirementsDTO } from '../model/models';
import { ShowGraduationRequirementsDTO } from '../model/models';
import { UpdateGraduationRequirementsDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GraduationRequirementsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param beltId 
     */
    apiGraduationRequirementsByBeltBeltIdGet(beltId: string, extraHttpRequestParams?: any): Observable<Array<ShowGraduationRequirementsDTO>>;

    /**
     * 
     * 
     */
    apiGraduationRequirementsGet(extraHttpRequestParams?: any): Observable<Array<ShowGraduationRequirementsDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    apiGraduationRequirementsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiGraduationRequirementsIdGet(id: string, extraHttpRequestParams?: any): Observable<ShowGraduationRequirementsDTO>;

    /**
     * 
     * 
     * @param id 
     * @param updateGraduationRequirementsDTO 
     */
    apiGraduationRequirementsIdPut(id: string, updateGraduationRequirementsDTO?: UpdateGraduationRequirementsDTO, extraHttpRequestParams?: any): Observable<ShowGraduationRequirementsDTO>;

    /**
     * 
     * 
     * @param createGraduationRequirementsDTO 
     */
    apiGraduationRequirementsPost(createGraduationRequirementsDTO?: CreateGraduationRequirementsDTO, extraHttpRequestParams?: any): Observable<ShowGraduationRequirementsDTO>;

}
