/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiAdminAcademiesIdGet404Response } from '../model/models';
import { CarlonGracieBackendProgressionApplicationDTOsCreateGraduationRequirementDTO } from '../model/models';
import { CarlonGracieBackendProgressionApplicationDTOsShowGraduationRequirementDTO } from '../model/models';
import { CarlonGracieBackendProgressionApplicationDTOsUpdateGraduationRequirementDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GraduationRequirementsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param beltId 
     */
    apiGraduationRequirementsByBeltBeltIdGet(beltId: string, extraHttpRequestParams?: any): Observable<Array<CarlonGracieBackendProgressionApplicationDTOsShowGraduationRequirementDTO>>;

    /**
     * 
     * 
     * @param $filter OData filter expression. Examples: contains(name,\&#39;John\&#39;) | status eq \&#39;Active\&#39; | amount gt 100 | createdAt ge 2024-01-01T00:00:00Z
     * @param $orderby Sort expression. Examples: name asc | createdAt desc | name asc,amount desc
     * @param $top Page size — number of records to return (default: 20, max: 200). Use with $skip for pagination.
     * @param $skip Records to skip. Use ($pageNumber - 1) * $top. Example: page 3 with size 20 → $skip&#x3D;40
     * @param $count Set to \&#39;true\&#39; to include total record count in response as @odata.count
     * @param $select Return only specific fields. Example: $select&#x3D;id,name,createdAt
     */
    apiGraduationRequirementsGet($filter?: string, $orderby?: string, $top?: string, $skip?: string, $count?: string, $select?: string, extraHttpRequestParams?: any): Observable<Array<CarlonGracieBackendProgressionApplicationDTOsShowGraduationRequirementDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    apiGraduationRequirementsIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiGraduationRequirementsIdGet(id: string, extraHttpRequestParams?: any): Observable<CarlonGracieBackendProgressionApplicationDTOsShowGraduationRequirementDTO>;

    /**
     * 
     * 
     * @param id 
     * @param carlonGracieBackendProgressionApplicationDTOsUpdateGraduationRequirementDTO 
     */
    apiGraduationRequirementsIdPut(id: string, carlonGracieBackendProgressionApplicationDTOsUpdateGraduationRequirementDTO?: CarlonGracieBackendProgressionApplicationDTOsUpdateGraduationRequirementDTO, extraHttpRequestParams?: any): Observable<CarlonGracieBackendProgressionApplicationDTOsShowGraduationRequirementDTO>;

    /**
     * 
     * 
     * @param carlonGracieBackendProgressionApplicationDTOsCreateGraduationRequirementDTO 
     */
    apiGraduationRequirementsPost(carlonGracieBackendProgressionApplicationDTOsCreateGraduationRequirementDTO?: CarlonGracieBackendProgressionApplicationDTOsCreateGraduationRequirementDTO, extraHttpRequestParams?: any): Observable<CarlonGracieBackendProgressionApplicationDTOsShowGraduationRequirementDTO>;

}
