/**
 * Carlson Gracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: support@carlsongracie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface HealthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    healthGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    healthLiveGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    healthReadyGet(extraHttpRequestParams?: any): Observable<{}>;

}
