/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiAdminAcademiesIdGet404Response } from '../model/models';
import { ApiMedicalClearanceIdAttachmentGet200Response } from '../model/models';
import { CarlonGracieBackendApplicationInterfacesInfrastructureChargeResult } from '../model/models';
import { CarlonGracieBackendApplicationInterfacesInfrastructureChargeStatus } from '../model/models';
import { CarlonGracieBackendFinancesApplicationDTOsPayMonthlyFeeDTO } from '../model/models';
import { CarlonGracieBackendFinancesApplicationDTOsShowMonthlyFeeDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MonthlyFeeServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param contractId 
     */
    apiMonthlyFeeContractContractIdGet(contractId: string, extraHttpRequestParams?: any): Observable<Array<CarlonGracieBackendFinancesApplicationDTOsShowMonthlyFeeDTO>>;

    /**
     * 
     * 
     * @param $filter OData filter expression. Examples: contains(name,\&#39;John\&#39;) | status eq \&#39;Active\&#39; | amount gt 100 | createdAt ge 2024-01-01T00:00:00Z
     * @param $orderby Sort expression. Examples: name asc | createdAt desc | name asc,amount desc
     * @param $top Page size — number of records to return (default: 20, max: 200). Use with $skip for pagination.
     * @param $skip Records to skip. Use ($pageNumber - 1) * $top. Example: page 3 with size 20 → $skip&#x3D;40
     * @param $count Set to \&#39;true\&#39; to include total record count in response as @odata.count
     * @param $select Return only specific fields. Example: $select&#x3D;id,name,createdAt
     */
    apiMonthlyFeeGet($filter?: string, $orderby?: string, $top?: string, $skip?: string, $count?: string, $select?: string, extraHttpRequestParams?: any): Observable<Array<CarlonGracieBackendFinancesApplicationDTOsShowMonthlyFeeDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    apiMonthlyFeeIdChargePost(id: string, extraHttpRequestParams?: any): Observable<CarlonGracieBackendApplicationInterfacesInfrastructureChargeResult>;

    /**
     * 
     * 
     * @param id 
     */
    apiMonthlyFeeIdChargeStatusGet(id: string, extraHttpRequestParams?: any): Observable<CarlonGracieBackendApplicationInterfacesInfrastructureChargeStatus>;

    /**
     * 
     * 
     * @param id 
     */
    apiMonthlyFeeIdGet(id: string, extraHttpRequestParams?: any): Observable<CarlonGracieBackendFinancesApplicationDTOsShowMonthlyFeeDTO>;

    /**
     * 
     * 
     * @param id 
     * @param carlonGracieBackendFinancesApplicationDTOsPayMonthlyFeeDTO 
     */
    apiMonthlyFeeIdPayPatch(id: string, carlonGracieBackendFinancesApplicationDTOsPayMonthlyFeeDTO?: CarlonGracieBackendFinancesApplicationDTOsPayMonthlyFeeDTO, extraHttpRequestParams?: any): Observable<CarlonGracieBackendFinancesApplicationDTOsShowMonthlyFeeDTO>;

    /**
     * 
     * 
     * @param id 
     */
    apiMonthlyFeeIdReceiptPdfGet(id: string, extraHttpRequestParams?: any): Observable<ApiMedicalClearanceIdAttachmentGet200Response>;

    /**
     * 
     * 
     */
    apiMonthlyFeeOverdueGet(extraHttpRequestParams?: any): Observable<Array<CarlonGracieBackendFinancesApplicationDTOsShowMonthlyFeeDTO>>;

    /**
     * 
     * 
     * @param studentId 
     */
    apiMonthlyFeeStudentStudentIdGet(studentId: string, extraHttpRequestParams?: any): Observable<Array<CarlonGracieBackendFinancesApplicationDTOsShowMonthlyFeeDTO>>;

}
