/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiFrequencyGetPageParameter } from '../model/models';
import { CreateNoticeDto } from '../model/models';
import { PaginatedResultOfShowNoticeDto } from '../model/models';
import { ProblemDetails } from '../model/models';
import { ShowNoticeDto } from '../model/models';
import { UpdateNoticeDto } from '../model/models';
import { ValidationProblemDetails } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface NoticesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param description 
     * @param isActive 
     * @param createdFrom 
     * @param createdTo 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiNoticesActiveGet(description?: string, isActive?: boolean, createdFrom?: string, createdTo?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowNoticeDto>;

    /**
     * 
     * 
     * @param description 
     * @param isActive 
     * @param createdFrom 
     * @param createdTo 
     * @param page 
     * @param pageSize 
     * @param orderBy 
     * @param orderByDescending 
     */
    apiNoticesGet(description?: string, isActive?: boolean, createdFrom?: string, createdTo?: string, page?: ApiFrequencyGetPageParameter, pageSize?: ApiFrequencyGetPageParameter, orderBy?: string, orderByDescending?: boolean, extraHttpRequestParams?: any): Observable<PaginatedResultOfShowNoticeDto>;

    /**
     * 
     * 
     * @param id 
     */
    apiNoticesIdDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param id 
     */
    apiNoticesIdGet(id: string, extraHttpRequestParams?: any): Observable<ShowNoticeDto>;

    /**
     * 
     * 
     * @param id 
     * @param updateNoticeDto 
     */
    apiNoticesIdPut(id: string, updateNoticeDto: UpdateNoticeDto, extraHttpRequestParams?: any): Observable<ShowNoticeDto>;

    /**
     * 
     * 
     * @param createNoticeDto 
     */
    apiNoticesPost(createNoticeDto: CreateNoticeDto, extraHttpRequestParams?: any): Observable<ShowNoticeDto>;

}
