/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface PublicStudentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param token 
     */
    apiPublicStudentsTokenConfirmPost(token: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param token 
     */
    apiPublicStudentsTokenGet(token: string, extraHttpRequestParams?: any): Observable<{}>;

}
