/**
 * API de Reconhecimento Facial com InsightFace
 * API para reconhecimento facial que suporta imagens com várias pessoas usando InsightFace
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { HTTPValidationError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Debug Headers
     * Debug endpoint to check what headers are being received
     */
    debugHeadersDebugHeadersGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Login
     * Login endpoint for username/password authentication. This endpoint is used by Swagger UI for authentication.
     * @param username 
     * @param password 
     * @param grantType 
     * @param scope 
     * @param clientId 
     * @param clientSecret 
     */
    loginTokenPost(username: string, password: string, grantType?: string, scope?: string, clientId?: string, clientSecret?: string, extraHttpRequestParams?: any): Observable<any>;

    /**
     * Read Root
     * 
     */
    readRootHealthGet(extraHttpRequestParams?: any): Observable<any>;

}
