/**
 * API de Reconhecimento Facial com InsightFace
 * API para reconhecimento facial que suporta imagens com várias pessoas usando InsightFace
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface DefaultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Debug Headers
     * Debug endpoint to check what headers are being received
     */
    debugHeadersDebugHeadersGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Metrics
     * Endpoint that serves Prometheus metrics.
     */
    metricsMetricsGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * Read Root
     * 
     */
    readRootHealthGet(extraHttpRequestParams?: any): Observable<any>;

}
