/**
 * API de Reconhecimento Facial com InsightFace
 * API para reconhecimento facial que suporta imagens com várias pessoas usando InsightFace
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RecognizedFace } from './recognizedFace';


/**
 * Schema for face recognition response
 */
export interface RecognitionResponse { 
    /**
     * Lista de faces reconhecidas
     */
    faces: Array<RecognizedFace>;
    processed_image?: string | null;
}

