/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AddressType = 'Comercial' | 'Residential';

export const AddressType = {
    Comercial: 'Comercial' as AddressType,
    Residential: 'Residential' as AddressType
};

