/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MicrosoftAspNetCoreMvcProblemDetails } from './microsoftAspNetCoreMvcProblemDetails';
import { MicrosoftAspNetCoreHttpHttpValidationProblemDetails } from './microsoftAspNetCoreHttpHttpValidationProblemDetails';


/**
 * @type ApiAdminAcademiesIdGet404Response
 * @export
 */
export type ApiAdminAcademiesIdGet404Response = MicrosoftAspNetCoreHttpHttpValidationProblemDetails | MicrosoftAspNetCoreMvcProblemDetails;

