/**
 * BjjClutch Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BaseStudentDTO { 
    userName: string;
    email: string;
    phoneNumber?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    birthDay?: string | null;
    isActive?: boolean;
}

