/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarlonGracieBackendSharedDomainEnumsTransactionType } from './carlonGracieBackendSharedDomainEnumsTransactionType';


export interface CarlonGracieBackendFinancesApplicationDTOsCreateTransactionDTO { 
    type?: CarlonGracieBackendSharedDomainEnumsTransactionType;
    transactionCategoryId?: string;
    description?: string | null;
    amount?: number;
    transactionDate?: string;
    reference?: string | null;
}
export namespace CarlonGracieBackendFinancesApplicationDTOsCreateTransactionDTO {
}


