/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarlonGracieBackendDomainEnumsTransactionType } from './carlonGracieBackendDomainEnumsTransactionType';


export interface CarlonGracieBackendDTOsTransactionFilterDTO { 
    type?: CarlonGracieBackendDomainEnumsTransactionType | null;
    transactionCategoryId?: string | null;
    dateFrom?: string | null;
    dateTo?: string | null;
    searchTerm?: string | null;
    pageNumber?: number;
    pageSize?: number;
}
export namespace CarlonGracieBackendDTOsTransactionFilterDTO {
}


