/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarlonGracieBackendSharedDomainEnumsTransactionType } from './carlonGracieBackendSharedDomainEnumsTransactionType';


export interface CarlonGracieBackendFinancesApplicationDTOsUpdateTransactionDTO { 
    type?: CarlonGracieBackendSharedDomainEnumsTransactionType | null;
    transactionCategoryId?: string | null;
    description?: string | null;
    amount?: number | null;
    transactionDate?: string | null;
    reference?: string | null;
}
export namespace CarlonGracieBackendFinancesApplicationDTOsUpdateTransactionDTO {
}


