/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarlonGracieBackendModelsNotificationType } from './carlonGracieBackendModelsNotificationType';


export interface CarlonGracieBackendDTOsNotificationFilterDTO { 
    searchTerm?: string | null;
    type?: CarlonGracieBackendModelsNotificationType | null;
    isActive?: boolean | null;
    studentId?: string | null;
    isExpired?: boolean | null;
    createdFrom?: string | null;
    createdTo?: string | null;
    expiresFrom?: string | null;
    expiresTo?: string | null;
    pageNumber?: number;
    pageSize?: number;
}
export namespace CarlonGracieBackendDTOsNotificationFilterDTO {
}


