/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarlonGracieBackendCommunicationsDomainNotificationType } from './carlonGracieBackendCommunicationsDomainNotificationType';


export interface CarlonGracieBackendCommunicationsApplicationDTOsCreateNotificationDto { 
    title?: string | null;
    message?: string | null;
    type?: CarlonGracieBackendCommunicationsDomainNotificationType;
    isActive?: boolean;
    expiresAt?: string | null;
    studentIds?: Array<string> | null;
}
export namespace CarlonGracieBackendCommunicationsApplicationDTOsCreateNotificationDto {
}


