/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CarlonGracieBackendDomainEnumsFeeStatus = 'Pending' | 'Paid' | 'Overdue' | 'Cancelled';

export const CarlonGracieBackendDomainEnumsFeeStatus = {
    Pending: 'Pending' as CarlonGracieBackendDomainEnumsFeeStatus,
    Paid: 'Paid' as CarlonGracieBackendDomainEnumsFeeStatus,
    Overdue: 'Overdue' as CarlonGracieBackendDomainEnumsFeeStatus,
    Cancelled: 'Cancelled' as CarlonGracieBackendDomainEnumsFeeStatus
};

