/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CarlonGracieBackendDomainEnumsFeeStatus } from './carlonGracieBackendDomainEnumsFeeStatus';


export interface CarlonGracieBackendDTOsMonthlyFeeFilterDTO { 
    searchTerm?: string | null;
    contractId?: string | null;
    studentId?: string | null;
    status?: CarlonGracieBackendDomainEnumsFeeStatus | null;
    dueDateFrom?: string | null;
    dueDateTo?: string | null;
    pageNumber?: number;
    pageSize?: number;
}
export namespace CarlonGracieBackendDTOsMonthlyFeeFilterDTO {
}


