/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FeeStatus = 'Pending' | 'Paid' | 'Overdue' | 'Cancelled';

export const FeeStatus = {
    Pending: 'Pending' as FeeStatus,
    Paid: 'Paid' as FeeStatus,
    Overdue: 'Overdue' as FeeStatus,
    Cancelled: 'Cancelled' as FeeStatus
};

