/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityTagHeaderValue } from './entityTagHeaderValue';


export interface FileResult { 
    contentType?: string | null;
    fileDownloadName?: string | null;
    lastModified?: string | null;
    entityTag?: EntityTagHeaderValue | null;
    enableRangeProcessing?: boolean;
}

