/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiFeePlanGetPriceMinParameter } from './apiFeePlanGetPriceMinParameter';
import { ApiFrequencyGetPageParameter } from './apiFrequencyGetPageParameter';


export interface FinancialSummaryDTO { 
    totalIncome?: ApiFeePlanGetPriceMinParameter;
    totalExpenses?: ApiFeePlanGetPriceMinParameter;
    balance?: ApiFeePlanGetPriceMinParameter;
    pendingFeesTotal?: ApiFeePlanGetPriceMinParameter;
    overdueFeeCount?: ApiFrequencyGetPageParameter;
    activeContractCount?: ApiFrequencyGetPageParameter;
}

