/**
 * Carlson Gracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: support@carlsongracie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Graduation } from './graduation';
import { Student } from './student';
import { Lesson } from './lesson';


export interface Frequency { 
    id?: string;
    studentId: string;
    student?: Student | null;
    graduationId: string;
    graduation?: Graduation | null;
    lessonId: string;
    lesson?: Lesson | null;
    createdAt?: string;
}

