/**
 * Carlson Gracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: support@carlsongracie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Frequency } from './frequency';


export interface Lesson { 
    id?: string;
    title?: string | null;
    description?: string | null;
    scheduledDate?: string;
    duration?: string;
    isActive?: boolean;
    createdAt?: string;
    frequencies?: Array<Frequency> | null;
}

