/**
 * BjjClutch Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MedicalClearanceAttachmentResponseDTO { 
    fileName?: string | null;
    contentType?: string | null;
    size?: number;
    s3Key?: string | null;
    uploadedAt?: string;
    message?: string | null;
}

