/**
 * BjjClutch Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MedicalClearanceStatsDTOClearancesByStatus } from './medicalClearanceStatsDTOClearancesByStatus';


export interface MedicalClearanceStatsDTO { 
    totalClearances?: number;
    approvedClearances?: number;
    pendingClearances?: number;
    rejectedClearances?: number;
    expiredClearances?: number;
    expiringSoonClearances?: number;
    clearancesByStatus?: MedicalClearanceStatsDTOClearancesByStatus | null;
    studentsWithValidClearance?: number;
    studentsWithoutClearance?: number;
}

