/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type NotificationType = 'Info' | 'Success' | 'Warning' | 'Error' | 'Graduation' | 'Lesson' | 'Payment' | 'System';

export const NotificationType = {
    Info: 'Info' as NotificationType,
    Success: 'Success' as NotificationType,
    Warning: 'Warning' as NotificationType,
    Error: 'Error' as NotificationType,
    Graduation: 'Graduation' as NotificationType,
    Lesson: 'Lesson' as NotificationType,
    Payment: 'Payment' as NotificationType,
    System: 'System' as NotificationType
};

