/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShowLessonScheduleDTO } from './showLessonScheduleDTO';
import { ApiFrequencyGetPageParameter } from './apiFrequencyGetPageParameter';


export interface PaginatedResultOfShowLessonScheduleDTO { 
    items?: Array<ShowLessonScheduleDTO>;
    totalCount?: ApiFrequencyGetPageParameter;
    page?: ApiFrequencyGetPageParameter;
    pageSize?: ApiFrequencyGetPageParameter;
    totalPages?: ApiFrequencyGetPageParameter;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;
}

