/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ScheduledJobCadence = 'Daily' | 'Weekly' | 'Monthly';

export const ScheduledJobCadence = {
    Daily: 'Daily' as ScheduledJobCadence,
    Weekly: 'Weekly' as ScheduledJobCadence,
    Monthly: 'Monthly' as ScheduledJobCadence
};

