/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateCompanyPersonDTO } from './createCompanyPersonDTO';
import { CreateAddressDTO } from './createAddressDTO';
import { CreateIndividualPersonDTO } from './createIndividualPersonDTO';


export interface ShowSupplierDTO { 
    id?: string;
    createdAt?: string;
    deletedAt?: string | null;
    individualPerson?: CreateIndividualPersonDTO | null;
    companyPerson?: CreateCompanyPersonDTO | null;
    addresses?: Array<CreateAddressDTO>;
}

