/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContractStatus } from './contractStatus';


export interface ShowContractDTO { 
    id?: string;
    studentId?: string;
    studentName?: string | null;
    feePlanId?: string;
    feePlanName?: string | null;
    feePlanMonthDuration?: number;
    startDate?: string;
    endDate?: string;
    monthlyAmount?: number;
    status?: ContractStatus;
    notes?: string | null;
    createdAt?: string;
    paidFees?: number;
    pendingFees?: number;
    overdueFees?: number;
}
export namespace ShowContractDTO {
}


