/**
 * Carlson Gracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: support@carlsongracie.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShowGraduationDTO { 
    id?: string;
    userName?: string | null;
    userEmail?: string | null;
    beltColor?: string | null;
    beltOrderIndex?: number | null;
    beltIsForKids?: boolean | null;
    studentId: string;
    beltId: string;
}

