/**
 * BjjClutch Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShowFrequencyDTO { 
    id?: string;
    createdAt?: string;
    studentId?: string;
    studentName?: string | null;
    graduationId?: string;
    lessonId?: string;
    lessonTitle?: string | null;
    lessonScheduledDate?: string;
}

