/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShowPaymentInformationDTO } from './showPaymentInformationDTO';
import { ApiFeePlanGetPriceMinParameter } from './apiFeePlanGetPriceMinParameter';
import { TransactionType } from './transactionType';
import { FeeStatus } from './feeStatus';
import { ChargeStatusConfirmedValue } from './chargeStatusConfirmedValue';


export interface ShowFinancialTransactionDTO { 
    createdAt?: string;
    id?: string;
    transactionCategoryName?: string;
    personName?: string | null;
    invoiceUrl?: string | null;
    pixQrCodeBase64?: string | null;
    pixCopyPaste?: string | null;
    externalChargeId?: string | null;
    dueDate?: string;
    type?: TransactionType;
    transactionCategoryId?: string | null;
    contractId?: string | null;
    status?: FeeStatus;
    personId?: string;
    paidAt?: string | null;
    paidAmount?: ChargeStatusConfirmedValue | null;
    description?: string;
    amount?: ApiFeePlanGetPriceMinParameter;
    transactionDate?: string;
    notes?: string | null;
    reference?: string | null;
    paymentInformation?: ShowPaymentInformationDTO;
}
export namespace ShowFinancialTransactionDTO {
}


