/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AsaasEnvironment } from './asaasEnvironment';
import { PaymentGatewayProvider } from './paymentGatewayProvider';


export interface ShowTenantSettingsDto { 
    paymentGateway: PaymentGatewayProvider;
    asaasApiKey: string | null;
    webhookSecret: string | null;
    asaasEnvironment: AsaasEnvironment;
}
export namespace ShowTenantSettingsDto {
}


