/**
 * BjjClutch Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionType } from './transactionType';


export interface UpdateTransactionDTO { 
    type?: TransactionType | null;
    transactionCategoryId?: string | null;
    description?: string | null;
    amount?: number | null;
    transactionDate?: string | null;
    reference?: string | null;
}
export namespace UpdateTransactionDTO {
}


