/**
 * CarlsonGracie Backend API
 * API for managing students, belts, graduation requirements, notices, frequencies and user authentication with Keycloak
 *
 * Contact: marcosturossi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProblemDetailsStatus } from './problemDetailsStatus';


export interface ValidationProblemDetails { 
    type?: string | null;
    title?: string | null;
    status?: ProblemDetailsStatus | null;
    detail?: string | null;
    instance?: string | null;
    errors?: { [key: string]: Array<string>; };
}

